In [19]:
import pandas as pd
from pandas import read_csv
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from scipy.stats import chi2_contingency
from statsmodels.stats import proportion

*1st Que. Cutlets Dataset*

In [20]:
data_cutlets = pd.read_csv("C:/Users/Dell/Downloads/Cutlets.csv")
data_cutlets.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [17]:
data_cutlets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Unit A  35 non-null     float64
 1   Unit B  35 non-null     float64
dtypes: float64(2)
memory usage: 688.0 bytes


In [24]:
p_value_cutlets = stats.ttest_ind(data_cutlets['Unit A'],data_cutlets['Unit B'])
p_value_cutlets

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

*2nd Que. labTAT Dataset*

In [25]:
data_labTAT=pd.read_csv("C:/Users/Dell/Downloads/LabTAT.csv")
data_labTAT.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [26]:
data_labTAT.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laboratory 1  120 non-null    float64
 1   Laboratory 2  120 non-null    float64
 2   Laboratory 3  120 non-null    float64
 3   Laboratory 4  120 non-null    float64
dtypes: float64(4)
memory usage: 3.9 KB


In [27]:
p_value_laabTAT= stats.f_oneway(data_labTAT['Laboratory 1'],data_labTAT['Laboratory 2'],data_labTAT['Laboratory 3'],data_labTAT['Laboratory 4'])
p_value_laabTAT

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

*3rd Que. BuyerRatio Dataset*

In [28]:
data_buyer=pd.read_csv('C:/Users/Dell/Downloads/BuyerRatio.csv')
data_buyer

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [29]:
data_buyer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Observed Values  2 non-null      object
 1   East             2 non-null      int64 
 2   West             2 non-null      int64 
 3   North            2 non-null      int64 
 4   South            2 non-null      int64 
dtypes: int64(4), object(1)
memory usage: 208.0+ bytes


In [30]:
ratio = np.array([[50,142,131,70],[435,1523,1356,750]])
ratio

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [32]:
stats.chi2_contingency([data_buyer["East"], data_buyer["West"], data_buyer["North"], data_buyer["South"]])

(1.5959455386610577,
 0.6603094907091882,
 3,
 array([[  42.76531299,  442.23468701],
        [ 146.81287862, 1518.18712138],
        [ 131.11756787, 1355.88243213],
        [  72.30424052,  747.69575948]]))

#P value of Chi2 is greater than alpha, therefore Ho is accepted.#

*4th Que. CustomerOrderForm Dataset*

In [33]:
data_CustomerOrderForm = pd.read_csv('C:/Users/Dell/Downloads/CostomerOrderForm.csv')
data_CustomerOrderForm

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [34]:
data_CustomerOrderForm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Phillippines  300 non-null    object
 1   Indonesia     300 non-null    object
 2   Malta         300 non-null    object
 3   India         300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB


In [36]:
stats.chi2_contingency([data_CustomerOrderForm['Phillippines'].value_counts(), data_CustomerOrderForm['Indonesia'].value_counts(), data_CustomerOrderForm['Malta'].value_counts(), data_CustomerOrderForm['India'].value_counts()])

(3.8589606858203545,
 0.2771020991233144,
 3,
 array([[271.75,  28.25],
        [271.75,  28.25],
        [271.75,  28.25],
        [271.75,  28.25]]))

#P value of Chi2 is greater than alpha, therefore Ho is accepted.#